### ISSUE TITLE
Inspections - when Inspection Completed = No, copy previous inspection

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#141] opened 2018-04-17 18:22 UTC
In General Information, when Inspection Completed = No, the system should duplicate the most recent inspection for this inspection.  The reason is that there is a legal requirement for inspectors to complete an inspection every single week.... so if they cannot due to snow, rain, etc., in their current workflow, they'll copy the previous inspection, change the date, and resubmit.  This is the intended workflow.  The steps below should achieve this.

When Inspection Completed = No and the user clicks the Save button in General Information, the system should:
1. Require a value for Noninspection Reason (this is functioning OK as is; no change needed)
2. Present a popup notification message, that indicates "_The inspection has not been completed.  The previous inspection will now be copied.  Please review the information, edit as necessary, and submit._"  This should include an OK button that the user must click before moving on.
3. Find the most recent submitted inspection for the associated project.
4. For the most recent submitted inspection, find all Present During Inspection records, and copy to the new inspection.
5. For the most recent submitted inspection, find all Inspection Specification records, and replicate the results in the new inspection.  So that if a spec was deficient in the most recent inspection, it is also a deficiency in the new inspection. 
6.  Notes should already be carrying over from one inspection to the next.  So no new functionality should have to happen here.
7. For the most recent submitted inspection, find all photos associated to that inspection, and copy to the new inspection.  This should include any associations to specifications and notes.
8. For the most recent submitted inspection, find all attachments associated to that inspection, and copy to the new inspection.  

Note that the following areas are not copied over:
**General Info** - the user will populate for the new inspection
**Notes** - the system should already be carrying these over from one inspection to the next
**Deficiencies** - these are not explicitly carried over, since they are derived from Specifications (which are carried over)
**Weather** - this is an automatic feed so no new functionality is required

**Comment by impittman** [comment] 2018-04-25 16:34
The following does not appear to be functioning:

2.Present a popup notification message, that indicates "The inspection has not been completed. The previous inspection will now be copied. Please review the information, edit as necessary, and submit." This should include an OK button that the user must click before moving on.  I see the following:
![message not updated](https://user-images.githubusercontent.com/16418393/39258960-cb443516-48a4-11e8-8bca-a3a13f6d4d43.png)

5.For the most recent submitted inspection, find all Inspection Specification records, and replicate the results in the new inspection. So that if a spec was deficient in the most recent inspection, it is also a deficiency in the new inspection. - This deficiencies did not carry over based on the last submitted inspection:
Last Inspection Submitted:
![bad spec](https://user-images.githubusercontent.com/16418393/39259488-0bd0cda0-48a6-11e8-9194-3ff2435f1835.png)

Copy of Inspection that Was set as "Not Complete"
![bad spec 2](https://user-images.githubusercontent.com/16418393/39259576-49efbba0-48a6-11e8-8152-56d99d14bf2e.png)

6.Notes should already be carrying over from one inspection to the next. So no new functionality should have to happen here. - Notes did not transfer over in the "Notes" Section of the Inspection.

**Comment by ehsan67** [comment] 2018-04-30 15:22
ready at kci

**Comment by impittman** [comment] 2018-05-10 02:17
@leeensminger  This is working as outlined for steps 1 - 6 above. However, 2 inspection records for the day where Inspection Completed = No are added. One is a duplicate inspection of the previous inspection and the other is an inspection record with no copied over data from the previous inspection.

Please confirm - There should be just 1 record created when Inspection Completed = No which is the duplicate copy of the previous inspection, not 2 as noted above, correct?

Red is the new record created and blue is the copied over inspection from the previous inspection.
![screenshot_1](https://user-images.githubusercontent.com/16418393/39848738-360ba1aa-53f8-11e8-8e32-a47b104e0577.png)

**Comment by leeensminger** [comment] 2018-05-16 13:33
@impittman Yes there should only be 1 resulting inspection, not two.

**Comment by impittman** [comment] 2018-05-16 13:45
@ehsan67 please see the 2 comments above (one from me and one from lee), only 1 inspection should result when an inspection complete = no.

**Comment by ehsan67** [comment] 2018-05-17 19:42
@impittman  I am not able to reproduce the problem, the process creates only one inspection and that is the copy of the last submitted inspection.

**Comment by impittman** [comment] 2018-05-17 22:47
@ehsan67 I cleared my browser and relogged in. Unfortunately, I am still getting the issue. Here is the steps used to help replicate what I am seeing:

-I used  896 Intersection for the Project. There were initially only 2 inspections in the project as shown below:
![starting point](https://user-images.githubusercontent.com/16418393/40207256-21c7cb02-5a23-11e8-9926-8da57d1696eb.png)
-I added a new inspection form and this worked fine. I would expect to see a new form with today's date and points at 409. It is highlighted in red below and has a status of not submitted.
![part 2 starting point](https://user-images.githubusercontent.com/16418393/40207278-44f943e4-5a23-11e8-9f99-665eef5275f2.png)
-I go to the General Info form for the inspection directly above and change the values to reflect Inspection Complete = No, change reason to "Too Wet" and click Save:
![values set](https://user-images.githubusercontent.com/16418393/40207325-72319af0-5a23-11e8-8185-391cc6522ed8.png)
-I now have 2 inspection records added for the inspection created today. One with today's date (in blue) and one with the copied over values from the last submitted inspection (in red). The one in blue (not copied over values) should not be present.
![ending issue](https://user-images.githubusercontent.com/16418393/40207387-cd1c1788-5a23-11e8-9ba0-600c81e489ff.png)

**Comment by ehsan67** [comment] 2018-05-18 17:01
@impittman @leeensminger  So based on Maria's example, does it mean that I need to delete the inspection when the user set Completed Inspection = No ?

**Comment by impittman** [comment] 2018-05-18 17:26
@ehsan67 @leeensminger  We want to delete the one in blue (non duplicate inspection). The duplicate inspection in red should remain in place.

**Comment by ehsan67** [comment] 2018-05-18 18:38
@impittman @leeensminger if we are deleting the inspection, what is the purpose of having the Reason dropdown?

**Comment by impittman** [comment] 2018-05-19 13:10
@ehsan67 @leeensminger 
For the duplicated inspection (the one red in my previous example), the workflow is to have the inspector keep all the inspection info the same from the last submitted inspection. However, the inspector will edit a few fields on the general info form before submitting:

-Inspection Date will be changed to the date the inspection was attempted. For example, if the last submitted inspection used for the duplicate inspection was 4/25/2018, the user would update it to be the date the inspection was attempted but not complete ex: 5/18/2018.

-Time in- This will be changed by inspector to the time the inspection was attempted on 5/18/2018 

-Time out- This will be changed by inspector to the time out on 5/18/2018.

-Inspection Complete = No

-Inspection Reason will need to show why the inspection was not complete.

-The associated notes, photos, deficiencies from the duplication process will not be edited. 

It is a way to show an inspection was attempted but not completed, the inspection reason will show why it was not completed, and all of the previous information from the last submitted inspection will remain intact for updates the next time an inspection is able to be completed.

**Comment by leeensminger** [comment] 2018-05-22 17:20
From General Information page:
inspection date = from new inspection
time in/out = from new inspection
last inspection date = same logic as is currently in place
construction status = use from previous submittted inspection
reason for inspection = use from previous submitted inspection
inspection completed = from new inspection
noninspection reason = from new inspection

all questions the system asks for the new inspection, will come from new inspection

**Comment by ehsan67** [comment] 2018-05-22 20:44
ready kci

**Comment by impittman** [comment] 2018-05-23 01:16
works as expected after testing, closing issue

**Closed as completed by impittman** 2018-05-23 01:16 UTC
Labels: functional bug, Ready for testing in next release
